### ISSUE TITLE
Allow narrow sidebar showing only icons without text - similar to pinned horizontal tabs.

### ISSUE THREAD

**Issue by vladski** [samihaddad/vertical-tabs-chrome-extension#13]

**Comment by samihaddad** [comment]
Do you mean for pinned tabs or all tabs?

**Comment by vladski** [comment]
For all tabs. Aa square buttons. And show text on mouse-over either as tooltip or expanding the button. It would be selectable by another option next to the "Compact view" e.g. "Button view" - see image:

<img width="874" alt="button-view" src="https://github.com/samihaddad/vertical-tabs-chrome-extension/assets/463686/7b635310-3be7-4553-828b-a0c1e7490096">

**Comment by samihaddad** [comment]
Unfortunately Chrome's side panel has a minimum width and can't be changed which prevents having this feature.
