### ISSUE TITLE
Saving tab groups

### ISSUE THREAD

**Issue by dmurat-croz** [samihaddad/vertical-tabs-chrome-extension#16]
This is a phenomenal extension :-)

However, I'm missing a feature for saving tab groups persistently.
Once the tab group is closed, it's gone forever. I would like to have the ability to save it for later, even if I close it.

**Comment by samihaddad** [comment]
Hey @dmurat-croz, glad you like it!

You can achieve this already using bookmarks. You can create a bookmark folder and then right click the folder and select 'Open All in New Tab Group' - this will also give the group a similar name as the bookmark folder.

**Comment by dmurat-croz** [comment]
tnx for tip
