### ISSUE TITLE
Double click the empty space of the vertical tab to open a new tab

### ISSUE THREAD

**Issue by Yra** [samihaddad/vertical-tabs-chrome-extension#17]
As the title, double clicking the empty space at the bottom of the vertical tab to open a new tab. (On top of the + sign at the bottom). At the same time, double click to close a tab.

**Comment by samihaddad** [comment]
Thanks for the feedback, I agree it might be a bit annoying to reach the + button when you don't have as much tabs. I think it's better to show the + at the bottom of the tabs when there's few tabs as double clicking on empty space won't be intuitive for users.

**Comment by samihaddad** [comment]
Added this to latest version.
