### ISSUE TITLE
Tab playing audio icon

### ISSUE THREAD

**Issue by StickNik** [samihaddad/vertical-tabs-chrome-extension#20]
Adding the little speaker icon that appears on tabs playing audio that allows you to mute the tab would be great.
Just the visual to help find an audio playing tab would be plenty, the mute function on a tab is useful though in some scenarios.

**Comment by samihaddad** [comment]
Hey! Great suggestion, I was planning to add an icon for media tabs with play/pause functionality but wasn't sure if Chrome allows it, if not will make it as mute/unmute. And btw you can already mute/unmute by right clicking a tab.

**Comment by samihaddad** [comment]
This is done, update to the latest version to check it out.

**Comment by StickNik** [comment]
Noticed the change and didn't even occur to me it might be from my suggestion, has been working flawlessly since, good work!
