### ISSUE TITLE
keyboard shortcut to hide & show the sidebar

### ISSUE THREAD

**Issue by holajoyce** [samihaddad/vertical-tabs-chrome-extension#23]
Great plugin!  It'd be amazing if we can have a keyboard shortcut to show & hide the sidebar.  Thank you!

**Comment by samihaddad** [comment]
Hey @holajoyce, thanks for the suggestion! Will be adding this soon, you can also set your own shortcut from chrome://extensions/shortcuts

**Comment by samihaddad** [comment]
This has been added already, alt+B is the default shortcut and can be changed as mentioned above.
