### ISSUE TITLE
Either change a word in right-click menu, and/or change the function

### ISSUE THREAD

**Issue by ODST05** [samihaddad/vertical-tabs-chrome-extension#24]
When you right-click a tab, the "Add Tab to New Window" should instead be "Move Tab to New Window". This is because the tab is removed from the original window. 

Alternatively, you could keep it as 'Add' and have the tab stay in the original window, as well as opening a copy in a new window. And/or add a new function that 'moves' the tab.

Great extension otherwise - thanks!

**Comment by samihaddad** [comment]
Thanks for reporting @ODST05, fixed the typo.
