### ISSUE TITLE
A hierarchie of tabs would be really great.

### ISSUE THREAD

**Issue by Harald-Koschinski** [samihaddad/vertical-tabs-chrome-extension#25]
In firefox we have "Tree Style Tab" - (https://piro.sakura.ne.jp/xul/_treestyletab.html.en)
I used it for many years - great stuff.
The feature is: When opening a Tab inside a Tab the new Tab is a child  -  one level down.

Kind regards
Harald

**Comment by samihaddad** [comment]
Hey @Harald-Koschinski, thanks for the suggestion. I believe this is similar to #14, I'll close this but feel free to move discussion there if anything is missing.
