### ISSUE TITLE
Scroll to selected tab

### ISSUE THREAD

**Issue by gliptak** [samihaddad/vertical-tabs-chrome-extension#31]
after opening in particular, the sidebar isn't scrolled to make the currently selected tab visible

this also seems to be the case on some other tab selection updates

**Comment by samihaddad** [comment]
Hey @gliptak, thanks for reporting this will make sure to fix it in next release.

**Comment by samihaddad** [comment]
This was added in latest version. Closing the ticket, please let me know if you find issues.
