### ISSUE TITLE
Tooltip on mouse over

### ISSUE THREAD

**Issue by vadimzee** [samihaddad/vertical-tabs-chrome-extension#39]
It would be great to show a full tab title content on the mouse over.

<img width="482" alt="Screenshot 2024-02-20 at 1 02 41 PM" src="https://github.com/samihaddad/vertical-tabs-chrome-extension/assets/30691082/80ebdf9a-2180-43e1-a439-f6541a921b17">

These are two different tabs with two different tab titles, but without seeing the full tab title, it is hard to see which is which.

**Comment by samihaddad** [comment]
Thanks for the suggestion, it's definitely useful. Will be adding it in the next release.

**Comment by samihaddad** [comment]
This was added a while back.
