### ISSUE TITLE
Auto-hide option

### ISSUE THREAD

**Issue by frblondin** [samihaddad/vertical-tabs-chrome-extension#46]
Great extension! I don't think there is a way to auto-hide Vertical Tabs, and expand it on hovering it with the mouse? That would allow to use the entire screen while reading a page.

What do you think?

**Comment by samihaddad** [comment]
Hey @frblondin, that would be a great improvement. Unfortunately, Chrome controls the side panel size and it can't be changed from an extension.

**Comment by frblondin** [comment]
That's what I was fearing. Understood!
