### ISSUE TITLE
No history or Bookmark Side Panel Option 

### ISSUE THREAD

**Issue by Amit10311** [samihaddad/vertical-tabs-chrome-extension#49]
Hello, 

I want to mention that I can't see a bookmark or history option in my side panel of vertical tabs. 

I like it, I didn't have to move much. I want to say that  I don't like the new updates. There are not many functions available apart from just watching my links.

**Comment by samihaddad** [comment]
Hey, Chrome is responsible for the bookmarks and history and with the new updates you will have to manually pin them. Check how to do it [here](https://support.google.com/chrome/answer/13156494?hl=en#zippy=%2Cpin-unpin-a-specific-side-panel).
