### ISSUE TITLE
Be able to narrow the width of vertical tabs sidebar to just show/fit the icons.

### ISSUE THREAD

**Issue by catalin-enache** [samihaddad/vertical-tabs-chrome-extension#51]
Thank you for the Vertical Tabs extension. 
f possible I think it would be great to be able to make the width of vertical tabs sidebar smaller.
Currently the minimum imposed width is too big and eats up too much from the entire screen.
I think a minimum width of 60px (or less) where only the icons should be visible would be good candidate for min width.
Thank you.

**Comment by samihaddad** [comment]
Hey @catalin-enache, this is controlled by Chrome you can check more info here https://github.com/samihaddad/vertical-tabs-chrome-extension/issues/42. You can upvote [this](https://issues.chromium.org/issues/40926440?pli=1) issue so it can get more visibility by Chrome team.

**Comment by catalin-enache** [comment]
@samihaddad , thanks for quick feedback. I went there and upvoted as suggested.
Cheers !
