### ISSUE TITLE
More elegant scroll bar for dark mode

### ISSUE THREAD

**Issue by longduc-nguyen** [samihaddad/vertical-tabs-chrome-extension#54]
I'm using a dark theme/dark mode and the scroll bar is a white-ish/grey-ish color. (when there's a lot of tabs)
Would be nice to have a dark scroll bar, like image
![scroll bar](https://github.com/samihaddad/vertical-tabs-chrome-extension/assets/48923949/a05b6063-df5c-4707-ba87-b847ff75678b)

**Comment by samihaddad** [comment]
Hey @longduc-nguyen, thanks for suggesting this. Finally came around to add it, you can find it in the latest version. I used a similar design to the Chrome scroll bar for light and dark mode.

**Comment by longduc-nguyen** [comment]
Sweet. Thanks!
