### ISSUE TITLE
Add a Top Row for Faviconized Pinned Tabs

### ISSUE THREAD

**Issue by MarvinMynx** [samihaddad/vertical-tabs-chrome-extension#6]
Add an Option to show Pinnend Tabs as Little Icons at the Top of the List Ordered Horizontally.

**Comment by samihaddad** [comment]
Hey @MarvinMynx, good suggestion. Are you thinking something similar to how Edge groups them at the top?

**Comment by MarvinMynx** [comment]
Yes exactly.

**Comment by oleschri** [comment]
You might have a look at how https://chrome.google.com/webstore/detail/vertical-tabs/pddljdmihkpdfpkgmbhdomeeifpklgnm does it.

**Comment by mabdelaal86** [comment]
I also would like to see this feature in this extension.

**Comment by samihaddad** [comment]
This has been added.
