### ISSUE TITLE
Ability to control the auto-update of the tab list

### ISSUE THREAD

**Issue by yshabanova** [samihaddad/vertical-tabs-chrome-extension#68]
When a group contains more than a screenful of tabs the auto-update keeps repositioning the view even when the list content did not change.
Either the previous center of the view should be preserved or a configuration added that would allow to control the auto-update (reduce frequency or disable/enable).

**Comment by samihaddad** [comment]
Thanks for the report, will disable autoscroll behavior for now.

**Comment by samihaddad** [comment]
This was re-enabled with better scrolling behaviour, let me know if you face any issues.
