### ISSUE TITLE
The sidebar doesn't scroll to the currently active tab anymore

### ISSUE THREAD

**Issue by thisistotallyfine** [samihaddad/vertical-tabs-chrome-extension#71]
In Google Chrome - if you switch to a tab which is not currently visible in the sidebar, the sidebar doesn't scroll up/down to the position of the tab.
This used to work fine before but seems to have recently stopped working. It becomes a problem once you have more than a handful of tabs and you need to start scrolling yourself to find out where the tab is located in the sidebar

**Comment by samihaddad** [comment]
This was re-enabled after fixing some bad behavior with the scrolling.

**Comment by thisistotallyfine** [comment]
nice, thanks for the quick fix
